# Project specific config
environment:
  matrix:
  - ATOM_CHANNEL: stable
  - ATOM_CHANNEL: beta

install:
  - choco install strawberryperl -y
  - SET PATH=C:\strawberry\c\bin;C:\strawberry\perl\site\bin;C:\strawberry\perl\bin;%PATH%
  - cpanm install Perl::Critic

# Generic setup follows
build_script:
  - perl --version
  - perlcritic --version
  - ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/atom/ci/master/build-package.ps1'))

branches:
  only:
    - master

version: "{build}"
platform: x64
clone_depth: 10
skip_tags: true
test: off
deploy: off
