version: 2

defaults: &defaults
  working_directory: /tmp/project
  docker:
    - image: arcanemagus/atom-docker-ci:stable
  steps:
    # Restore project state
    - attach_workspace:
        at: /tmp
    # Restore App::cpanminus cache
    - restore_cache:
        keys:
        # Get latest cache for the current specs
        - v1-cpanminus-{{ arch }}-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}
        # Fall back to the latest for the current branch
        - v1-cpanminus-{{ arch }}-{{ .Branch }}-
        # Fall back to the latest for master
        - v1-cpanminus-{{ arch }}-master-
        # Don't fall back any further
    - run:
        name: Install Perl
        command: |
          sudo apt-get update && \
          sudo apt-get install --assume-yes --quiet \
            --no-install-suggests --no-install-recommends \
            perl cpanminus
    - run:
        name: Perl version
        command: perl --version
    - run:
        name: App::cpanminus version
        command: cpanm --version
    - run:
        name: Configure local Perl lib path
        command: |
          cpanm --local-lib=~/perl5 local::lib && \
          eval $(perl -I ~/perl5/lib/perl5/ -Mlocal::lib) && \
          echo 'export PERL5LIB=/home/atom/perl5/lib/perl5' >> $BASH_ENV && \
          echo 'export PERL_LOCAL_LIB_ROOT=/home/atom/perl5' >> $BASH_ENV && \
          echo 'export PERL_MB_OPT="--install_base \"/home/atom/perl5\""' >> $BASH_ENV && \
          echo 'export PERL_MM_OPT=INSTALL_BASE=/home/atom/perl5' >> $BASH_ENV && \
          echo 'export PATH="/home/atom/perl5/bin:$PATH"' >> $BASH_ENV
    - run:
        name: Install Perl::Critic
        command: cpanm install Perl::Critic
    - run:
        name: Perl::Critic version
        command: perlcritic --version
    - run:
        name: Create VFB for Atom to run in
        command: /usr/local/bin/xvfb_start
    - run:
        name: Atom version
        command: ${ATOM_SCRIPT_PATH} --version
    - run:
        name: APM version
        command: ${APM_SCRIPT_PATH} --version
    - run:
        name: Package APM package dependencies
        command: |
          if [ -n "${APM_TEST_PACKAGES}" ]; then
            for pack in ${APM_TEST_PACKAGES}; do
            ${APM_SCRIPT_PATH} install "${pack}"
            done
          fi;
    - run:
        name: Package dependencies
        command: ${APM_SCRIPT_PATH} install
    - run:
        name: Cleaning package
        command: ${APM_SCRIPT_PATH} clean
    - run:
        name: Package specs
        command: ${ATOM_SCRIPT_PATH} --test spec
    # Cache node_modules
    - save_cache:
        paths:
          - node_modules
        key: v3-dependencies-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json"}}
    # Cache Perl Modules
    - save_cache:
        paths:
          - "~/perl5"
        key: v1-cpanminus-{{ arch }}-{{ .Branch }}-{{ checksum ".circleci/config.yml" }}

jobs:
  checkout_code:
    <<: *defaults
    docker:
      - image: circleci/node:latest
    steps:
      - checkout
      # Restore node_modules from the last build
      - restore_cache:
          keys:
          # Get latest cache for this package.json and pacakge-lock.json
          - v3-dependencies-{{ .Branch }}-{{ checksum "package.json" }}-{{ checksum "package-lock.json"}}
          # Fallback to the current package.json
          - v3-dependencies-{{ .Branch }}-{{ checksum "package.json" }}-
          # Fallback to the last build for this branch
          - v3-dependencies-{{ .Branch }}-
          # Fallback to the last available master branch cache
          - v3-dependencies-master-
          # Don't go further down to prevent dependency issues from other branches
      # Save project state for next steps
      - persist_to_workspace:
          root: /tmp
          paths:
            - project
  lint:
    <<: *defaults
    docker:
      - image: circleci/node:latest
    steps:
      # Restore project state
      - attach_workspace:
          at: /tmp
      - run:
          name: Node.js Version
          command: node --version
      - run:
          name: NPM Version
          command: npm --version
      - run:
          name: Install any remaining dependencies
          command: npm install
      - run:
          name: Lint code
          command: npm run lint
  stable:
    <<: *defaults
  beta:
    <<: *defaults
    docker:
      - image: arcanemagus/atom-docker-ci:beta

workflows:
  version: 2
  test_package:
    jobs:
      - checkout_code
      - lint:
          requires:
            - checkout_code
      - stable:
          requires:
            - lint
      - beta:
          requires:
            - lint
